apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: 544378344870.dkr.ecr.us-east-1.amazonaws.com/clo835-week4:mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: your_root_password_here
          ports:
            - containerPort: 3306
