apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: 544378344870.dkr.ecr.us-east-1.amazonaws.com/clo835-week4:app
          ports:
            - containerPort: 8080
