apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  namespace: myapp
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: myapp-rs-container
          image: 544378344870.dkr.ecr.us-east-1.amazonaws.com/clo835-week4:app
          env:
            - name: DBHOST
              value: "10.244.0.19"
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: mydb-secret
                  key: user
            - name: DATABASE
              value: "employees"
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: mydb-secret
                  key: password
            - name: APP_COLOR
              value: "blue"
            ports:
              - containerPort: 80
          dnsPolicy: ClusterFirst
          restartPolicy: Always  
          
          
          
          
          
          
          ports:
            - containerPort: 8080
        dnsPolicy: ClusterFirst
        restartPolicy: Always