apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: myapp-container
      image: 544378344870.dkr.ecr.us-east-1.amazonaws.com/clo835-week4:app
      env:
            - name: DBHOST
              value: "172.17.0.2"
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: "root"
            - name: DATABASE
              value: "employees"
            - name: DBPWD
              value: "pw"
            - name: APP_COLOR
              value: "blue"
              
      ports:
        - containerPort: 8080
